ALTER TABLE ZIPCODE_INFO
ALTER COLUMN CITY VARCHAR(25);

ALTER TABLE ZIPCODE_INFO
ADD STATE VARCHAR(2);

EXEC sp_help 'ZIPCODE_INFO';
GO
ALTER TABLE INSTRUCTOR_INFO
ALTER COLUMN INSTRUCTOR_FIRST_NAME VARCHAR(25);

ALTER TABLE INSTRUCTOR_INFO
ALTER COLUMN INSTRUCTOR_LAST_NAME VARCHAR(25);

ALTER TABLE INSTRUCTOR_INFO
ADD STREET_ADDRESS VARCHAR(50);

ALTER TABLE INSTRUCTOR_INFO
ADD ZIP_CODE VARCHAR(5);

EXEC sp_help 'INSTRUCTOR_INFO';
GO
ALTER TABLE COURSE_INFO
ADD COURSE_NAME VARCHAR(50);

ALTER TABLE COURSE_INFO
ADD COURSE_PREREQUISITE NUMERIC(8,0);

ALTER TABLE COURSE_INFO
ALTER COLUMN COST NUMERIC(9,2);

EXEC sp_help 'COURSE_INFO';
GO
ALTER TABLE STUDENT_INFO
ALTER COLUMN STUDENT_FIRST_NAME VARCHAR(25);

ALTER TABLE STUDENT_INFO
ALTER COLUMN STUDENT_LAST_NAME VARCHAR(25);

ALTER TABLE STUDENT_INFO
ADD STREET_ADDRESS VARCHAR(50);

ALTER TABLE STUDENT_INFO
ADD ZIP_CODE VARCHAR(5);

EXEC sp_help 'STUDENT_INFO';
GO
ALTER TABLE SECTION_INFO
ALTER COLUMN SECTION_NO NUMERIC(3,0);

ALTER TABLE SECTION_INFO
ADD LOCATION VARCHAR(50);

ALTER TABLE SECTION_INFO
ADD CAPACITY NUMERIC(3,0);

EXEC sp_help 'SECTION_INFO';
GO
ALTER TABLE ENROLLMENT_INFO
ADD ENROLLMENT_DATE DATE;

EXEC sp_help 'ENROLLMENT_INFO';
GO
ALTER TABLE GRADE_INFO
ALTER COLUMN GRADE_CODE_OCCURANCE NUMERIC(38,0);

ALTER TABLE GRADE_INFO
ADD NUMERIC_GRADE NUMERIC(3,0);

EXEC sp_help 'GRADE_INFO';
GO