-- Equi Join
-- 1. Display the course and the section information.
SELECT C.COURSE_NO,
       C.COURSE_NAME,
       C.COST,
       S.SECTION_ID,
       S.SECTION_NO,
       S.LOCATION,
       S.CAPACITY
FROM COURSE_INFO C
JOIN SECTION_INFO S
ON C.COURSE_NO = S.COURSE_NO;
-- 2. Display the instructor details along with the city and state.
SELECT I.*,
       Z.CITY,
       Z.STATE
FROM INSTRUCTOR_INFO I
JOIN ZIPCODE_INFO Z
ON I.ZIP_CODE = Z.ZIP_CODE;
-- 3. Display the student details, city and state. Sort by ZIP Code.
SELECT S.*,
       Z.CITY,
       Z.STATE
FROM STUDENT_INFO S
JOIN ZIPCODE_INFO Z
ON S.ZIP_CODE = Z.ZIP_CODE
ORDER BY S.ZIP_CODE;
-- 4. Display first and last names of enrolled students.
SELECT DISTINCT
       S.STUDENT_FIRST_NAME,
       S.STUDENT_LAST_NAME
FROM STUDENT_INFO S
JOIN ENROLLMENT_INFO E
ON S.STUDENT_ID = E.STUDENT_ID
ORDER BY S.STUDENT_LAST_NAME DESC;
-- 5. Display ZIP, city, state and instructor names living in NY.
SELECT
Z.ZIP_CODE,
Z.CITY,
Z.STATE,
I.INSTRUCTOR_FIRST_NAME,
I.INSTRUCTOR_LAST_NAME
FROM INSTRUCTOR_INFO I
JOIN ZIPCODE_INFO Z
ON I.ZIP_CODE=Z.ZIP_CODE
WHERE Z.STATE='NY';
-- 6. Students enrolled in Course 20 on January 30, 2000.
SELECT
E.STUDENT_ID,
S.COURSE_NO,
E.ENROLLMENT_DATE,
E.SECTION_ID
FROM ENROLLMENT_INFO E
JOIN SECTION_INFO S
ON E.SECTION_ID=S.SECTION_ID
WHERE S.COURSE_NO=20
AND E.ENROLLMENT_DATE='2000-01-30';
-- 7. Display course, section and instructor.
SELECT
C.COURSE_NO,
C.COURSE_NAME,
C.COST,
S.SECTION_ID,
I.INSTRUCTOR_FIRST_NAME,
I.INSTRUCTOR_LAST_NAME
FROM COURSE_INFO C
JOIN SECTION_INFO S
ON C.COURSE_NO=S.COURSE_NO
JOIN INSTRUCTOR_INFO I
ON S.INSTRUCTOR_ID=I.INSTRUCTOR_ID;
-- 8. Student 220 Section 119 grades.
SELECT
G.STUDENT_ID,
G.SECTION_ID,
G.GRADE_TYPE_CODE,
G.NUMERIC_GRADE,
DATENAME(MONTH,E.ENROLLMENT_DATE) AS ENROLL_MONTH
FROM GRADE_INFO G
JOIN ENROLLMENT_INFO E
ON G.STUDENT_ID=E.STUDENT_ID
AND G.SECTION_ID=E.SECTION_ID
WHERE G.STUDENT_ID=220
AND G.SECTION_ID=119;
-- 9. Students where instructor lives in ZIP 10025 and course has no prerequisite.
SELECT
E.STUDENT_ID,
S.COURSE_NO,
S.SECTION_NO
FROM ENROLLMENT_INFO E
JOIN SECTION_INFO S
ON E.SECTION_ID=S.SECTION_ID
JOIN INSTRUCTOR_INFO I
ON S.INSTRUCTOR_ID=I.INSTRUCTOR_ID
JOIN COURSE_INFO C
ON S.COURSE_NO=C.COURSE_NO
WHERE I.ZIP_CODE='10025'
AND C.COURSE_PREREQUISITE IS NULL;
-- 10. Instructor details teaching Section No 2.
SELECT
I.*,
Z.CITY,
Z.STATE
FROM INSTRUCTOR_INFO I
JOIN SECTION_INFO S
ON I.INSTRUCTOR_ID=S.INSTRUCTOR_ID
JOIN ZIPCODE_INFO Z
ON I.ZIP_CODE=Z.ZIP_CODE
WHERE S.SECTION_NO=2;
-- 11. Student IDs living in CT.
SELECT DISTINCT
E.STUDENT_ID
FROM ENROLLMENT_INFO E
JOIN STUDENT_INFO S
ON E.STUDENT_ID=S.STUDENT_ID
JOIN ZIPCODE_INFO Z
ON S.ZIP_CODE=Z.ZIP_CODE
WHERE Z.STATE='CT';
-- 12. Details of student Fenny Crawford for Section 86.
SELECT
S.*,
E.SECTION_ID,
E.ENROLLMENT_DATE
FROM STUDENT_INFO S
JOIN ENROLLMENT_INFO E
ON S.STUDENT_ID=E.STUDENT_ID
WHERE S.STUDENT_FIRST_NAME='Fenny'
AND S.STUDENT_LAST_NAME='Crawford'
AND E.SECTION_ID=86;
-- 13. Final examination grades of NY students in Course 300.
SELECT
S.*,
G.NUMERIC_GRADE
FROM STUDENT_INFO S
JOIN ZIPCODE_INFO Z
ON S.ZIP_CODE=Z.ZIP_CODE
JOIN ENROLLMENT_INFO E
ON S.STUDENT_ID=E.STUDENT_ID
JOIN SECTION_INFO SEC
ON E.SECTION_ID=SEC.SECTION_ID
JOIN GRADE_INFO G
ON E.STUDENT_ID=G.STUDENT_ID
AND E.SECTION_ID=G.SECTION_ID
WHERE Z.STATE='NY'
AND SEC.COURSE_NO=300
AND G.GRADE_TYPE_CODE='FI';
-- 14. Students scoring 75 or below in Project.
SELECT
G.STUDENT_ID,
G.SECTION_ID,
G.NUMERIC_GRADE,
S.STUDENT_LAST_NAME
FROM GRADE_INFO G
JOIN STUDENT_INFO S
ON G.STUDENT_ID=S.STUDENT_ID
WHERE G.NUMERIC_GRADE<=75
AND G.GRADE_TYPE_CODE='PJ';
OUTER JOIN
-- 1. Courses with or without sections.
SELECT
C.COURSE_NO,
C.COURSE_NAME,
C.COURSE_PREREQUISITE,
S.SECTION_ID
FROM COURSE_INFO C
LEFT JOIN SECTION_INFO S
ON C.COURSE_NO=S.COURSE_NO;
-- 2. Include courses having no instructor.
SELECT
C.COURSE_NO,
C.COURSE_NAME,
S.SECTION_ID,
I.INSTRUCTOR_FIRST_NAME,
I.INSTRUCTOR_LAST_NAME
FROM COURSE_INFO C
LEFT JOIN SECTION_INFO S
ON C.COURSE_NO=S.COURSE_NO
LEFT JOIN INSTRUCTOR_INFO I
ON S.INSTRUCTOR_ID=I.INSTRUCTOR_ID;
-- 3. Students 102 and 301 even if not enrolled or graded.
SELECT
ST.STUDENT_ID,
E.SECTION_ID,
G.NUMERIC_GRADE,
G.GRADE_TYPE_CODE
FROM STUDENT_INFO ST
LEFT JOIN ENROLLMENT_INFO E
ON ST.STUDENT_ID=E.STUDENT_ID
LEFT JOIN GRADE_INFO G
ON E.STUDENT_ID=G.STUDENT_ID
AND E.SECTION_ID=G.SECTION_ID
WHERE ST.STUDENT_ID IN (102,301);
SELF JOIN
-- 1. Course with prerequisite description.
SELECT
C1.COURSE_NO,
C1.COURSE_NAME,
C2.COURSE_NO AS PREREQUISITE,
C2.COURSE_NAME AS PREREQUISITE_NAME
FROM COURSE_INFO C1
JOIN COURSE_INFO C2
ON C1.COURSE_PREREQUISITE=C2.COURSE_NO;

-- 2. Students in Section 86 whose Final grade is lower than Midterm.
SELECT
FI.STUDENT_ID,
FI.GRADE_TYPE_CODE AS FINAL_TYPE,
FI.NUMERIC_GRADE AS FINAL_GRADE,
MT.GRADE_TYPE_CODE AS MIDTERM_TYPE,
MT.NUMERIC_GRADE AS MIDTERM_GRADE
FROM GRADE_INFO FI
JOIN GRADE_INFO MT
ON FI.STUDENT_ID=MT.STUDENT_ID
AND FI.SECTION_ID=MT.SECTION_ID
WHERE FI.SECTION_ID=86
AND FI.GRADE_TYPE_CODE='FI'
AND MT.GRADE_TYPE_CODE='MT'
AND FI.NUMERIC_GRADE<MT.NUMERIC_GRADE;
-- 3. Display the names of the students.

SELECT
STUDENT_FIRST_NAME,
STUDENT_LAST_NAME
FROM STUDENT_INFO;